# Generated by Django 3.2.5 on 2021-07-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpics',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ManyToManyField(to='blog.BlogPics'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpics',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
