# Generated by Django 3.2.5 on 2021-07-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210706_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpics',
            name='image',
            field=models.FileField(upload_to='blog'),
        ),
    ]
